### ISSUE TITLE
Crashes game upon start

### ISSUE THREAD

**Issue by ShA-FR** [AMGarkin/BDO-GuildQuestMod#1] opened 2018-05-09 12:57 UTC
Looks like they're comparing file size just speculation.
Currently outdated for EU/NA.

**Comment by AMGarkin** [comment] 2018-05-09 14:25
Doesn't work anymore because .loc files are compressed using some new and currently unknown method.
If anyone knows how to extract text files from new .loc files let me know.

**Comment by ShA-FR** [comment] 2018-05-09 14:26
Will take a look at it thank you for the reply!

**Comment by AMGarkin** [comment] 2018-05-09 14:30
BTW crash is caused by damaged loc files after using this tool. Delete file /ads/langVersion.dat and then let launcher update loc files, it should fix it.

**Comment by ShA-FR** [comment] 2018-05-09 14:53
Yeah, thanks noticed it, about .loc files are the game UI / language in .loc too?

Because I remember using: http://sotgame.com/ to get Chinese localization so if it's .loc too they might find a way around it, sorry if I say much bullshit stuff just trying to help.

**Comment by AMGarkin** [comment] 2018-05-12 11:45
I found out that new .loc file is compressed using ZLIB (first 4 bytes are header - size of uncompressed file in bytes and rest of the file are compressed data). However extracted file is not usual .txt file, but .bss file.

If you want to try extract data from the file, you can use for example [Offzip](http://aluigi.altervista.org/mytoolz.htm#offzip) tool:
`offzip -a languagedata_en.loc . 4`

**Comment by bachrixv** [comment] 2018-05-13 02:31
So.. now we know how to extract it.. 

then how to compressed the file in to that new .loc format ?

**Comment by AMGarkin** [comment] 2018-05-13 13:00
I have some tools to compress and decompress .loc / .bss files ([BDOcrypt-beta.zip](https://github.com/AMGarkin/BDO-GuildQuestMod/files/1998462/BDOcrypt-beta.zip)), but in order to make this mod working, I will have to write also converter between .bss and readable .txt format.

**Comment by AMGarkin** [comment] 2018-05-14 12:47
What I have so far: 
[BDOcrypt-alpha.zip](https://github.com/AMGarkin/BDO-GuildQuestMod/files/2000682/BDOcrypt-alpha.zip)
I'm planning to move functions from bss<->txt converter directly into BDOcrypt, this is just "draft version".

Now I have to modify ReplaceLanguage for this new format and convert replace_??.txt patterns from UTF-8 to UTF-16.

**Comment by m3Noa** [comment] 2018-05-14 15:15
Thanks for your hard work. Much appreciate.

However, when I tried to encrypt unmodified .bss back to .loc, the file size is much smaller and causes the game crashed. I think the compression method is a bit off.

**Comment by AMGarkin** [comment] 2018-05-14 17:28
It's about compression level, game uses Z_BEST_SPEED, I have used Z_DEFAULT_COMPRESSION.
Game was working correctly with default setting for me, but I can change it to make files identical. Recompiled with Z_BEST_SPEED:
[BDO_encrypt-alpha2.zip](https://github.com/AMGarkin/BDO-GuildQuestMod/files/2001899/BDO_encrypt-alpha2.zip)

**Comment by AMGarkin** [comment] 2018-05-14 19:14
BDOcrypt updated: https://github.com/AMGarkin/BDOcrypt

**Comment by bachrixv** [comment] 2018-05-14 22:47
Nice.. it works for me.. even though i need to replace it manually.. now i will wait till u fix ReplaceLanguage.. 

You are the best.. keep up the good work.. /^.^)/

**Comment by m3Noa** [comment] 2018-05-15 02:02
I tried the new BDOcrypt, just run the .exe to decrypt and encrypt back, dont know if there is something wrong with my computer or not, cuz the output files are empty.

Commands I use:
```
bdo_decrypt.exe languagedata_en.loc languagedata_en.bss
bdo_encrypt.exe languagedata_en.bss languagedata_en_new.loc
```
![cryptcmd](https://user-images.githubusercontent.com/39271786/40032519-a37eea38-581e-11e8-9638-660fa76f50ef.jpeg)

**Comment by AMGarkin** [comment] 2018-05-15 03:39
Do you use the latest files? (https://github.com/AMGarkin/BDOcrypt/releases).
BDO_decrypt now contains functions from BDO_bss2txt and BDO_encrypt contains functions from BDO_txt2bss.

I was able to induce issue where new .loc file converted from .txt was incomplete, but it always contains a few MBs of data.

**Comment by m3Noa** [comment] 2018-05-15 03:52
Yes, that's the one I used.

Just tried again with these commands like in the README file, but still the same result:
`bdo_decrypt.exe languagedata_en.loc languagedata_en.txt
bdo_encrypt.exe languagedata_en.txt languagedata_en_new.loc`

**Comment by Shadowtrance** [comment] 2018-05-15 03:58
Works no issue here. able to decrypt / encrypt the new files no problem with the latest release of bdocrypt.
I suspect the issue is somewhere on your end @m3Noa :(

Any progress on replacelanguage @AMGarkin ?

**Comment by m3Noa** [comment] 2018-05-15 04:05
Hmm...  After I set both encrypt.exe and decrypt.exe to run as Administrator, it works.
But I was able to run normally when using the one one: [BDOcrypt-alpha.zip](https://github.com/AMGarkin/BDO-GuildQuestMod/files/2000682/BDOcrypt-alpha.zip)

**Comment by AMGarkin** [comment] 2018-05-15 04:07
@Shadowtrance ReplaceLanguage should be working now:
https://github.com/AMGarkin/ReplaceLanguage/releases/tag/2.0

**Comment by Shadowtrance** [comment] 2018-05-15 04:25
Yep just saw that. Sadly it isn't replacing though. hmm
Stop changing shit PA! haha

Anyway, the output i get from that is...

> Reading "replace_en.txt"... (1 lines found)
> Copying lines from "languagedata_en.txt" to "languagedata_en.new"...
> Processed lines: 475135 (translated: 0, original: 475135)
> Done!

Tried both the replace_en.txt from here and my copy of that one edited to be similar to the converted loc file. Both with the same result.

**Comment by m3Noa** [comment] 2018-05-15 04:29
Well, @Shadowtrance you probably still use the old replace_en.txt file which is in UTF-8. You need to convert it to UTF-16 for it to work :)

**Comment by Shadowtrance** [comment] 2018-05-15 04:31
hmm good point. lol

**Comment by m3Noa** [comment] 2018-05-15 04:42
Just tested. Converting the old file to UTF-16 is not gonna work. Need to manually make a new replace.txt in UTF-16 for it lol

**Comment by Shadowtrance** [comment] 2018-05-15 05:05
I got it to work with my edited replace_en.txt

Game would just crash using the old one with korean still in it. (even after converting like below)

I "converted" it to utf16 (i just made a copy of the converted loc file txt - which notepad++ shows as "**UCS-2 LE w/o BOM**", deleted everything in it and replaced it with what was in replace_en.txt) after i edited it to be similar to the converted loc file txt and now it works no probs. Converting other ways didn't seem to work for some reason, resulted in crashing.

My edited file for reference.
[replace_en.txt](https://github.com/AMGarkin/BDO-GuildQuestMod/files/2003510/replace_en.txt)

**Comment by AMGarkin** [comment] 2018-05-15 11:32
I have uploaded replace_??.txt in new format.

BTW in Notepad++ you can use replace with regular expression to convert old replace_??.txt:
Find what: ^([0-9]+\t[0-9]+\t[0-9]+\t[0-9]+\t[0-9]+\t)([^\t]+\t)([^\t]+)\t([^\n]+)
Replace with: \1"\3"
When converting file make sure that .txt file has Windows-like end of line characters (CR+LF, 0x000D+0x000A), BDOcrypt will crash (create incomplete file) if you use UNIX-like end of line (just LF).

The only issue in Notepad++ is that if you use it for encoding conversion, it will store BOM mark. So you'll have to delete 1st 2 bytes from file (0xFF 0xFE). I'll probably update tools to ignore BOM...

**Comment by AMGarkin** [comment] 2018-05-15 12:57
Issue should be fixed now, Tool correctly update .loc file and game won't crash upon start.

**Closed as completed by AMGarkin** 2018-05-15 12:57 UTC
